### ISSUE TITLE
Documentation should be extended to cover non K64F boards OoB#5

### ISSUE THREAD

**Issue by bulislaw** [ARMmbed/mbed-os-example-tls#10]
README file should be extended to cover non-K64F use cases:

- Explicitly mention that at this stage other boards are not supported, otherwise people are faced with:
```
plaintext message: 536f6d65207468696e67732061726520626574746572206c65667420756e7265616400
Example failed with error 1
```
which doesn't mean much for them
- Documentation should enable people to implement support for TLS on their boards. It should be documented what is required (and what needs to be done) to get the demo up and running on different boards

CC: @rhenson

**Comment by sbutcher-arm** [comment]
This is not an issue for mbed TLS, but more the lack of support for mbed TLS in mbed OS at the time you tested the issue.

To answer your point - 'It should be documented what is required' - the answer is very simply a board that supports mbed TLS which is dependent on hardware driver support. I think that is better documented in mbed OS, not in an mbed TLS example, where we're going to find it hard to track what mbed OS supports and what it doesn't.

**Comment by yanesca** [comment]
Also I it may be relevant, that I had updated the `Readme.md` with an "Other hardware" section right after this issue was raised.
