### ISSUE TITLE
[OoB_5.8]: Opaque key handling example does not compile in online compiler

### ISSUE THREAD

**Issue by ashok-rao** [ARMmbed/mbed-os-example-tls#158]
Steps to reproduce:
1. Import example via GitHub URL.
2. Switch to "feature-opaque-key" branch.
3. Select K64 as target.
4. Compile.

Expected output:
Example builds and generates binary.

Actual output:
Example does not build. Screenshot below.
![tls_onlinecompiler](https://user-images.githubusercontent.com/17567812/37670931-6cada0cc-2c62-11e8-835e-8ef2cc515ace.JPG)

**Comment by ashok-rao** [comment]
cc @mazimkhan

**Comment by sbutcher-arm** [comment]
@Patater - Given this related to opaque key handling, can we close it?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2424

**Comment by Patater** [comment]
The opaque keys work will be delivered differently as part of [Mbed Crypto](https://github.com/ARMmbed/mbed-crypto). Closing.
