### ISSUE TITLE
Remove todo from the benchmark application

### ISSUE THREAD

**Issue by RonEld** [ARMmbed/mbed-os-example-tls#170]
Remove the `todo` struct from the benchmark application, as it is a legacy from the origin of the example

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2420

**Comment by andresag01** [comment]
@sbutcher-arm, @RonEld: I think this was fixed by https://github.com/ARMmbed/mbed-os-example-tls/pull/194. Should we close this issue

**Comment by andresag01** [comment]
This was fixed via https://github.com/ARMmbed/mbed-os-example-tls/pull/194, so it can now be closed.
