### ISSUE TITLE
benchmark application: TIME_AND_TSC doesn't check return code

### ISSUE THREAD

**Issue by RonEld** [ARMmbed/mbed-os-example-tls#172]
The return code of function calls in `TIME_AND_TSC` is not checked

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2418

**Comment by andresag01** [comment]
@sbutcher-arm, @RonEld: I think this was fixed by https://github.com/ARMmbed/mbed-os-example-tls/pull/194. Should we close this issue

**Comment by andresag01** [comment]
This issue has been fixed via #194, so can now be closed.
