### ISSUE TITLE
benchmark application uses printf instead of mbedtls_printf

### ISSUE THREAD

**Issue by RonEld** [ARMmbed/mbed-os-example-tls#185]
[benchmark.c](https://github.com/ARMmbed/mbed-os-example-tls/blame/master/benchmark/main.cpp#L1022) contains `printf()` instead of the abstraction`mbedtls_printf()`

**Comment by andresag01** [comment]
@sbutcher-arm, @RonEld: I think this was fixed by https://github.com/ARMmbed/mbed-os-example-tls/pull/194. Should we close this issue

**Comment by andresag01** [comment]
This was fixed via https://github.com/ARMmbed/mbed-os-example-tls/pull/194, so it can now be closed.
