### ISSUE TITLE
Benchmark example times out on KW24D, on ARM compiler

### ISSUE THREAD

**Issue by k-stachowiak** [ARMmbed/mbed-os-example-tls#210]
The example times out while performing benchmark for `DHE-2048`. Surrounding log:

```
[1540134513.96][CONN][RXD]   RSA-4096                 :   20077 ms/private
[1540134527.98][HTST][INF] test suite run finished after 600.77 sec...
[1540134527.98][HTST][ERR] Expected output [\s+DHE-2048\s*:\s*\d+ ms/handshake] not received in log.
```

**Comment by k-stachowiak** [comment]
Note that it is similar to #208

**Comment by RonEld** [comment]
@k-stachowiak Does the example timeout when setting `MBEDTLS_MPI_MAX_SIZE` to 512 ?

**Comment by k-stachowiak** [comment]
@sbutcher-arm @Patater Based on #231 I conclude, that the problem doesn't occur anymore. I suggest closing this issue.

**Comment by ciarmcom** [comment]
@k-stachowiak thank you for raising this issue.Please take a look at the following comments:

Could you add some more detail to the description? A good description should be at least 25 words.
What target(s) are you using?
What toolchain(s) are you using?
What version of Mbed OS are you using (tag or sha)?
It would help if you could also specify the versions of any tools you are using?
How can we reproduce your issue?

NOTE: If there are fields which are not applicable then please just add 'n/a' or 'None'.This indicates to us that at least all the fields have been considered.
Please update the issue header with the missing information, the issue will not be mirroredto our internal defect tracking system or investigated until this has been fully resolved.

**Comment by ciarmcom** [comment]
@k-stachowiak it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@k-stachowiak it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@k-stachowiak it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@k-stachowiak it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@k-stachowiak it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by k-stachowiak** [comment]
I still think we can close it. Let me free some @ciarmcom 's cycles and close it.
