### ISSUE TITLE
Compiling tls-client with IAR compiler throws warnings

### ISSUE THREAD

**Issue by andresag01** [ARMmbed/mbed-os-example-tls#27]
Compiling the tls-client example with IAR causes the following warning to be printed to the console:
```
[Warning] ssl_srv.c@2684,0: [Pe549]: variable "len" is used before its value is set
```
This warning was observed while compiling with mbed-os-5.3.0-rc1 and mbed-cli. To reproduce run the command:
```
cd tls-client
mbed compile -m K64F -t IAR
```

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1111

**Comment by andresag01** [comment]
This is an mbed TLS problem and is being addressed in https://github.com/ARMmbed/mbedtls/pull/750

**Comment by andresag01** [comment]
The PR that fixes this issue in Mbed TLS has already been merged. The change is also in Mbed OS and the library version that the examples are using already includes the fixes needed for IAR. This ticket can now be closed.
