### ISSUE TITLE
README should let users know the benchmark app takes a long time to run

### ISSUE THREAD

**Issue by LDong-Arm** [ARMmbed/mbed-os-example-tls#299]
### Description of defect

The RSA-4096 generation test in the benchmark app takes several minutes to run, potentially over 10 minutes on some targets. We should let users know this is normal and the application is not frozen - they should wait longer.

#### Target(s) affected by this defect ?

Any

#### Toolchain(s) (name and version) displaying this defect ?

Any

#### What version of Mbed-os are you using (tag or sha) ?

mbed-os-6.11.0

#### What version(s) of tools are you using. List all that apply (E.g. mbed-cli)

N/A

#### How is this defect reproduced ?

Compile and run the benchmark app.

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTOSM-4079*

**Comment by LDong-Arm** [comment]
Fixed by #300
