### ISSUE TITLE
tls-client example does not support Wifi

### ISSUE THREAD

**Issue by andresag01** [ARMmbed/mbed-os-example-tls#43]
The tls-client application only works with Ethernet at the moment. It needs to be modified so that it uses either Wifi or Ethernet depending on availability.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1181

**Comment by andresag01** [comment]
This issue has been resolved via https://github.com/ARMmbed/mbed-os-example-tls/pull/101. Closing...
