### ISSUE TITLE
[OOB_5_4] tls-client got "SSL - Memory allocation failed"

### ISSUE THREAD

**Issue by soramame21** [ARMmbed/mbed-os-example-tls#54]
I got following error when running tls-client on **NUCLEO_F746ZG**.
It related memory handling by IAR compiler. 
![allocation_err](https://cloud.githubusercontent.com/assets/17120422/23493992/1cdc8000-ff53-11e6-9eb7-81e1698e3729.png)

# How to build the bad executable
1.
> mbed compile -m NUCLEO_F746ZG -t IAR -c > bb0 2>&1
2.
> mbed export -i IAR -m NUCLEO_F746ZG -vv > aa 2>&1
then click **Make**,  **Download and Debug** on IAR Embedded Workbench.
3.

> mbed export -i make_iar -m NUCLEO_F746ZG -vv > a00 2>&1
> make clean
> make V=1 > ren02 2>&1

# How to build a working executable
> mbed compile -m NUCLEO_F746ZG -t GCC_ARM -c > bb2 2>&1

**Comment by soramame21** [comment]
@simonb @MarceloSalazar Could you give comment for this issue?

**Comment by sbutcher-arm** [comment]
Looks like a memory problem. The suspicion is the heap isn't big enough with IAR.

@mazimkhan - Can you please look at this?

**Comment by mazimkhan** [comment]
@soramame21 please try with latest mbed-os that has fix for the memory issue.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1248

**Comment by soramame21** [comment]
@mazimkhan I'll try it tomorrow. thanks.

**Comment by mazimkhan** [comment]
This PR fixed this issue in mbed-os https://github.com/ARMmbed/mbed-os/pull/3871

**Comment by mazimkhan** [comment]
Please try with this PR on mbed-os
https://github.com/ARMmbed/mbed-os/issues/3902

**Comment by mazimkhan** [comment]
Updated my comment above. This issue should be fixed by ARMmbed/mbed-os#3902

**Comment by MarceloSalazar** [comment]
I confirm PR ARMmbed/mbed-os#3902 fixes memory allocation problem when building with IAR
@0xc0170 please add a note to the mbed OS known issue list

**Comment by soramame21** [comment]
@mazimkhan @MarceloSalazar yes, I verified the fix for IAR toolchain as well.

**Comment by mazimkhan** [comment]
Can this be closed now?
