### ISSUE TITLE
wrong output in the Benchmark application

### ISSUE THREAD

**Issue by RonEld** [ARMmbed/mbed-os-example-tls#69]
The output of the Benchmark Application performance is in Kb/s , however, according to the code:
~~~
    mbedtls_printf( "%9lu Kb/s,  %9lu cycles/byte\r\n",                        \
                     i * BUFSIZE / 1024,                                       \
                     ( mbedtls_timing_hardclock() - tsc ) / ( j * BUFSIZE ) );
~~~
The performance should be in Kilo Bytes (KB) not Kilo bits (Kb) as printed

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1286

**Comment by andresag01** [comment]
A fix for this issue has already been merged into master. Closing ticket...

**Comment by RonEld** [comment]
@andresag01 I think this issue was remained opened because of the benchmark application in the mbed TLS repository: https://github.com/ARMmbed/mbedtls/pull/920

**Comment by RonEld** [comment]
my mistakes, I thought about the internal JIRA ticket
