### ISSUE TITLE
[Benchmark] Remove dependencies on DWT registers

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/mbed-os-example-tls#74]
The application should not access to DWT/Debug registers directly. Also, these registers are only available in ARMv7-M based processors (not in Cortex-M0/M0+).

https://github.com/ARMmbed/mbed-os-example-tls/blob/master/benchmark/main.cpp#L189

I'd suggest to use the 'time' API available in mbed OS:
https://docs.mbed.com/docs/mbed-os-api-reference/en/latest/APIs/tasks/Time/

@sbutcher-arm

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1302

**Comment by andresag01** [comment]
https://github.com/ARMmbed/mbed-os-example-tls/pull/88 addresses this issue.

**Comment by andresag01** [comment]
PR #88 has now been merged. This issue should be resolved.
