### ISSUE TITLE
Compiling tls examples with Keil throws warnings 

### ISSUE THREAD

**Issue by deepikabhavnani** [ARMmbed/mbed-os-example-tls#90]
Compiling "tls examples" with Keil gives multiple warnings with freescale target device
           warning:  #66-D: enumeration value is out of "int" range

Steps to reproduce run the command:
1. Clone "mbed-os-example-tls"
2. Enter authcrypt directory
3. mbed deploy
4. mbed export -i uVision -m K64F
5. Build code on Keil uVision

@sg-  @maclobdell @mmahadevan108 : enums are used for register specific defines (unsigned int) in target specific code and as per C standard range of enum is limited to int. Hence we see out of range warning for enums.

**Comment by andresag01** [comment]
@deepikabhavnani: Thank you for raising this issue.

The files that are raising the #66-D warning are `fsl_dspi.h`, `fsl_edma.h` and `fsl_uart.h`. However, none of these belong to mbed TLS or this examples repository, so I will close this issue. Also, please note that there is already a ticket in mbed OS that reports this problem: https://github.com/ARMmbed/mbed-os/issues/4222.
